import { Link } from "react-router-dom";
import { usePageTitle } from "../../hooks/usePageTitle";
import LegalPageLayout from "../../components/legal/LegalPageLayout";

export default function PrivacyPolicy() {
  usePageTitle("Privacy Policy");

  return (
    <LegalPageLayout
      title="Glass Finance — Privacy Policy"
      effectiveDate="1st of August, 2026"
      lastUpdated="1st of August, 2026"
    >
      <p>
        This Privacy Policy explains how Glass Finance Limited ("Glass," "we," "us," "our")
        collects, uses, discloses, and protects personal information when you use the Glass
        website, mobile applications, dashboards, and related services (the "Platform").
        Capitalized terms not defined here have the meaning given in the{" "}
        <Link to="/terms">Terms of Service</Link>.
      </p>
      <p>
        This Policy applies to Community Owners, Community Administrators, Members, Guests,
        and Organizations, and should be read together with our{" "}
        <Link to="/terms">Terms of Service</Link>, <Link to="/cookies">Cookie Policy</Link>,
        and <Link to="/acceptable-use">Acceptable Use Policy</Link>.
      </p>

      <h2>1. Scope</h2>
      <p>
        This Policy covers personal information processed by Glass Finance Limited as a data
        controller (for Account-level and Platform-operation data) and, in relation to certain
        Community data, as a data processor acting on the instructions of the Community Owner
        or Organization. Where Glass processes Member data on behalf of a Community, the
        Community remains responsible, as data controller, for ensuring it has a lawful basis
        to collect and share that data with Glass.
      </p>

      <h2>2. Categories of Information We Collect</h2>
      <p>We collect the following categories of personal information ("Personal Information"):</p>
      <ul>
        <li><strong>Identity Information</strong>: full name, date of birth, gender, government-issued ID numbers (e.g., BVN, NIN, passport, driver's license, where required for KYC), photograph, and signature.</li>
        <li><strong>Payment Information</strong>: card details (tokenized by our Payment Processor, not stored by Glass in raw form), bank account details, transaction history, Dues and Contribution records, payout details.</li>
        <li><strong>Community Data</strong>: Community name, description, logo, membership lists, roles and permissions, internal Community records that Community Owners or Administrators upload or generate on the Platform.</li>
        <li><strong>Usage Data</strong>: pages visited, features used, timestamps, click patterns, session duration, and similar interaction data.</li>
        <li><strong>Device Information</strong>: device type, operating system, browser type, IP address, unique device identifiers, and mobile network information.</li>
        <li><strong>Cookies and Similar Technologies</strong>: as described in our <Link to="/cookies">Cookie Policy</Link>.</li>
        <li><strong>Analytics Data</strong>: aggregated or pseudonymized usage patterns used to improve the Platform.</li>
        <li><strong>Location Data</strong>: general location derived from IP address, and precise location only where you separately grant device-level permission (e.g., for fraud checks or localized services).</li>
        <li><strong>Communications</strong>: emails, SMS messages, support tickets, in-app messages, and call recordings (where applicable and disclosed at the time) between you and Glass.</li>
        <li><strong>KYC Information</strong>: information submitted to or generated by our KYC Provider (Smile ID), including verification status, liveness-check results, and document images.</li>
      </ul>

      <h2>3. How We Collect Information</h2>
      <p>
        We collect Personal Information: (a) directly from you, when you register, complete
        KYC, make or receive a payment, or contact support; (b) automatically, through your use
        of the Platform (cookies, device data, usage logs); and (c) from third parties,
        including Payment Processors, KYC Providers, Community Owners/Administrators (who may
        upload Member information), and, where lawful, publicly available sources for fraud and
        compliance screening.
      </p>

      <h2>4. How We Use Information</h2>
      <p>We use Personal Information to:</p>
      <ul>
        <li>create and manage Accounts, Communities, and Member records;</li>
        <li>process payments, Dues, Contributions, and payouts;</li>
        <li>verify identity and comply with KYC/AML obligations;</li>
        <li>detect, investigate, and prevent fraud, money laundering, and other prohibited activity;</li>
        <li>provide customer support and respond to inquiries;</li>
        <li>send transactional notifications (payment confirmations, receipts, reminders) via email and SMS;</li>
        <li>send marketing communications, where you have opted in or as otherwise permitted by Applicable Law;</li>
        <li>generate dashboards, reports, and exports for Community Administrators;</li>
        <li>maintain audit logs and security records;</li>
        <li>improve, secure, and develop the Platform, including through aggregated analytics;</li>
        <li>comply with legal, regulatory, and law enforcement obligations;</li>
        <li>enforce our Terms of Service and Acceptable Use Policy.</li>
      </ul>

      <h2>5. Legal Bases for Processing</h2>
      <p>
        Where the Nigeria Data Protection Act 2023 and the Nigeria Data Protection Regulation
        ("NDPR"), the GDPR, UK GDPR, or similar law applies, we rely on the following legal
        bases, as applicable:
      </p>
      <ul>
        <li><strong>Contractual necessity</strong> — to perform our obligations under the Terms of Service (e.g., processing a payment you initiate).</li>
        <li><strong>Legal obligation</strong> — to comply with KYC, AML, tax, and other regulatory requirements.</li>
        <li><strong>Legitimate interests</strong> — for fraud prevention, Platform security, service improvement, and direct marketing to existing customers, balanced against your rights and interests.</li>
        <li><strong>Consent</strong> — for optional marketing communications, non-essential cookies, and precise location access, which you may withdraw at any time.</li>
        <li><strong>Vital interests</strong> — in rare cases, to protect the life or safety of an individual.</li>
      </ul>

      <h2>6. How We Share Information</h2>
      <p>
        We do not sell Personal Information. We share Personal Information only as described in
        this Policy, including with:
      </p>
      <ul>
        <li>Payment Processors (Section 7);</li>
        <li>KYC Providers (Section 8);</li>
        <li>Cloud and infrastructure providers (Section 9);</li>
        <li>Regulators and law enforcement (Section 10);</li>
        <li>Community Owners and Administrators, who receive Member payment status, contact details, and related records necessary to administer their Community;</li>
        <li>Professional advisors (lawyers, auditors, accountants) under confidentiality obligations;</li>
        <li>A successor entity, in connection with a merger, acquisition, financing, or sale of assets, subject to continued protection under this Policy or a materially similar policy;</li>
        <li>Other third parties, only with your consent or as required by Applicable Law.</li>
      </ul>

      <h2>7. Payment Providers</h2>
      <p>
        We share transaction data (amount, payer and payee identity, payment method details)
        with our Payment Processor, currently Paystack, to process and settle transactions.
        Paystack processes this data under its own privacy policy and applicable card network
        and banking regulations. Glass does not store full card numbers; card data is tokenized
        and handled by Paystack in accordance with PCI-DSS standards.
      </p>

      <h2>8. Identity Providers</h2>
      <p>
        We share identity documents and biometric verification data with our KYC Provider,
        currently Smile ID, solely to verify identity and comply with AML/KYC obligations. Smile
        ID processes this data under its own privacy policy and applicable data protection
        standards.
      </p>

      <h2>9. Cloud and Infrastructure Providers</h2>
      <p>
        We use AWS for cloud hosting and data storage, Vercel for application hosting, Resend
        for transactional email delivery, Termii for SMS delivery, and Google Workspace for
        internal productivity and communication tools. These providers process Personal
        Information on our behalf under data processing agreements and are contractually
        restricted from using your data for their own purposes.
      </p>

      <h2>10. Regulators and Law Enforcement</h2>
      <p>
        We may disclose Personal Information to the Central Bank of Nigeria (CBN), the Nigeria
        Financial Intelligence Unit (NFIU), the Nigeria Data Protection Commission (NDPC),
        courts, or other competent regulators or law enforcement agencies where required by
        Applicable Law, in response to a valid legal request, or where necessary to protect the
        rights, property, or safety of Glass, our Users, or the public.
      </p>

      <h2>11. Cookies and Analytics</h2>
      <p>
        We use cookies and similar technologies as described in our{" "}
        <Link to="/cookies">Cookie Policy</Link>, which is
        incorporated into this Policy by reference. We use analytics tools to understand
        aggregate Platform usage; where technically feasible, analytics data is pseudonymized.
      </p>

      <h2>12. Location Data</h2>
      <p>
        We derive approximate location from your IP address for fraud detection, regulatory
        compliance (e.g., confirming you are accessing the Platform from a permitted
        jurisdiction), and localization. Where an application requests precise device location,
        this is used only for the stated purpose and only with your permission, which you may
        withdraw through your device settings.
      </p>

      <h2>13. Communications</h2>
      <p>
        We may send you transactional communications (e.g., payment receipts, security alerts,
        KYC requests) related to your use of the Platform; these are necessary to the Services
        and cannot be opted out of while your Account remains active. We may also send
        marketing communications where you have opted in, which you may opt out of at any time
        as described in Section 21.
      </p>

      <h2>14. Cross-Border Data Transfers</h2>
      <p>
        14.1 Personal Information may be transferred to and processed in countries outside
        Nigeria, including where our infrastructure providers (such as AWS) operate data
        centers, or where a Payment Processor or KYC Provider processes data outside Nigeria.
      </p>
      <p>
        14.2 Where we transfer Personal Information outside Nigeria, we do so in compliance
        with the Nigeria Data Protection Act 2023 and NDPR cross-border transfer requirements,
        including by relying on adequacy determinations, standard contractual clauses, binding
        corporate rules, or other lawful transfer mechanisms, and by verifying that the
        recipient jurisdiction or entity provides an adequate level of protection.
      </p>
      <p>
        14.3 Where GDPR or UK GDPR applies to your Personal Information, we rely on adequacy
        decisions or appropriate safeguards, such as Standard Contractual Clauses, for
        transfers outside the European Economic Area or United Kingdom.
      </p>

      <h2>15. Data Retention</h2>
      <p>
        15.1 We retain Personal Information for as long as necessary to fulfill the purposes
        described in this Policy, including:
      </p>
      <ul>
        <li>Account and transaction records: for the duration of the Account plus a minimum retention period required for financial record-keeping under Nigerian law (generally at least six (6) years from the date of the transaction, or longer if required by a regulator or ongoing legal proceeding);</li>
        <li>KYC records: for the retention period required under applicable AML/KYC regulations;</li>
        <li>Marketing consent records: until consent is withdrawn, plus a reasonable period to evidence compliance;</li>
        <li>Support communications: for a reasonable period to resolve disputes and improve service quality.</li>
      </ul>
      <p>
        15.2 Where retention is no longer necessary, we securely delete or anonymize Personal
        Information, subject to Section 22.
      </p>

      <h2>16. Security Measures</h2>
      <p>
        We implement technical and organizational measures designed to protect Personal
        Information, including encryption in transit and at rest, access controls and
        role-based permissions, network security monitoring, regular security assessments, and
        employee confidentiality obligations. No system is completely secure, and we cannot
        guarantee absolute security; we will notify affected Users and, where required,
        regulators, in the event of a data breach likely to result in a risk to your rights, in
        accordance with Applicable Law.
      </p>

      <h2>17. Children's Privacy</h2>
      <p>
        The Platform is not directed at children under 13. Members between 13 and 18 may use
        the Platform only under the supervision of a Community Administrator, in accordance
        with Section 2 of the Terms of Service, and only the minimum Personal Information
        necessary for Community administration is collected in that context. We do not
        knowingly collect Personal Information from children under 13. If we learn that we have
        inadvertently collected such information, we will take steps to delete it, and a parent
        or guardian may contact us at the address in Section 25 to request deletion.
      </p>

      <h2>18. Your Data Subject Rights</h2>
      <p>Subject to Applicable Law and to verification of your identity, you have the right to:</p>
      <ul>
        <li>access the Personal Information we hold about you;</li>
        <li>request correction of inaccurate or incomplete Personal Information;</li>
        <li>request deletion of your Personal Information, subject to Section 22;</li>
        <li>object to or restrict certain processing, including direct marketing;</li>
        <li>request a copy of your Personal Information in a portable format;</li>
        <li>withdraw consent where processing is based on consent, without affecting the lawfulness of prior processing.</li>
      </ul>
      <p>
        We will respond to verified requests within the timeframes required by Applicable Law
        (generally within thirty (30) days, extendable where permitted).
      </p>

      <h2>19. NDPR Rights (Nigeria)</h2>
      <p>
        If you are located in Nigeria, you have rights under the Nigeria Data Protection Act
        2023 and the NDPR, including the rights described in Section 18, as well as the right
        to lodge a complaint with the Nigeria Data Protection Commission (NDPC) if you believe
        your rights have been violated.
      </p>

      <h2>20. GDPR / UK GDPR Rights</h2>
      <p>
        If you are located in the European Economic Area or United Kingdom, you have the
        rights described in Section 18 under the GDPR or UK GDPR, as applicable, and the right
        to lodge a complaint with your local data protection supervisory authority.
      </p>

      <h2>21. Marketing Preferences</h2>
      <p>
        You may opt in or out of marketing communications at any time by using the unsubscribe
        link in emails, adjusting notification settings within the Platform, or contacting us
        at the address in Section 25. Opting out of marketing does not affect transactional
        communications necessary for the operation of your Account.
      </p>

      <h2>22. Data Deletion</h2>
      <p>
        22.1 You may request deletion of your Account and associated Personal Information by
        contacting us at the address in Section 25.
      </p>
      <p>
        22.2 We may retain certain information notwithstanding a deletion request where
        retention is required to comply with legal, regulatory, tax, or AML/KYC obligations, to
        resolve disputes, to enforce our agreements, or to maintain accurate financial records
        for a Community's audit purposes. Where full deletion is not possible, we will
        anonymize the data where feasible.
      </p>
      <p>
        22.3 Deletion of a Member's Personal Information may be subject to the Community
        Owner's own record-keeping obligations for the underlying Dues or Contributions.
      </p>

      <h2>23. Complaints</h2>
      <p>
        If you believe we have not complied with this Policy or Applicable Law, please contact
        us at the address in Section 25 first. If you are not satisfied with our response, you
        may lodge a complaint with the Nigeria Data Protection Commission (NDPC) or, where
        applicable, your local data protection supervisory authority.
      </p>

      <h2>24. Changes to This Policy</h2>
      <p>
        We may update this Policy from time to time. Material changes will be communicated
        through the Platform, email, or other reasonable means, with an updated "Last Updated"
        date. Continued use of the Platform after changes take effect constitutes acceptance of
        the revised Policy.
      </p>

      <h2>25. Contact Us</h2>
      <p>
        Data Protection Officer / Privacy Team<br />
        Glass Finance Limited<br />
        Email: <a href="mailto:privacy@glasspay.app">privacy@glasspay.app</a><br />
        Address: 1, Onyemergwu Close, Abule Egba, Lagos
      </p>
      <p>For general Platform questions, see the Terms of Service, Section 33.</p>
    </LegalPageLayout>
  );
}
