import { Link } from "react-router-dom";
import { usePageTitle } from "../../hooks/usePageTitle";
import LegalPageLayout from "../../components/legal/LegalPageLayout";

export default function TermsOfService() {
  usePageTitle("Terms of Service");

  return (
    <LegalPageLayout
      title="Glass Finance — Terms of Service"
      effectiveDate="1st of August, 2026"
      lastUpdated="1st of August, 2026"
    >
      <p>
        These Terms of Service ("Terms," "Agreement") are a binding legal agreement between
        Glass Finance Limited ("Glass," "we," "us," or "our"), a company incorporated under the
        laws of the Federal Republic of Nigeria, and you ("you," "your," or "User"), governing
        your access to and use of the Glass website, mobile applications, dashboards, APIs, and
        related services (collectively, the "Platform" or "Services").
      </p>
      <p>
        By creating an account, accessing, or using the Platform, you agree to be bound by
        these Terms, our <Link to="/privacy">Privacy Policy</Link>,{" "}
        <Link to="/cookies">Cookie Policy</Link>,{" "}
        <Link to="/acceptable-use">Acceptable Use Policy</Link>, and{" "}
        <Link to="/refund-policy">Refund Policy</Link>, each of which is incorporated into
        this Agreement by reference. If you do not agree, you must not use the Platform.
      </p>

      <h2>1. Definitions</h2>
      <p>
        The following defined terms apply across this Agreement and, where used, across the{" "}
        <Link to="/privacy">Privacy Policy</Link>, <Link to="/cookies">Cookie Policy</Link>,{" "}
        <Link to="/acceptable-use">Acceptable Use Policy</Link>, and{" "}
        <Link to="/refund-policy">Refund Policy</Link>:
      </p>
      <ul>
        <li><strong>"Account"</strong> means a Glass user profile, whether held by an Individual, a Community, or an Organization.</li>
        <li><strong>"Community"</strong> means a group, association, cooperative, religious organization, school, club, NGO, alumni body, student organization, or similar body that uses Glass to collect Dues or Contributions from its Members.</li>
        <li><strong>"Community Owner"</strong> means the individual or Organization that creates and holds ultimate administrative control over a Community's Glass account.</li>
        <li><strong>"Community Administrator"</strong> means a user granted administrative permissions over a Community by a Community Owner. Glass currently supports three Community roles — Community Owner, Community Administrator, and Community Member (Member) — and may introduce additional or more granular roles (such as Treasurer, Financial Officer, or Moderator) in the future.</li>
        <li><strong>"Guest"</strong> means a person who makes a one-time payment through Glass without creating a full Account.</li>
        <li><strong>"Member"</strong> means an individual who joins a Community on Glass to make or track payments, whether or not they hold an independent Glass Account.</li>
        <li><strong>"Organization"</strong> means a legal entity (registered or unregistered) that uses Glass, including its authorized representatives.</li>
        <li><strong>"Dues"</strong> or <strong>"Contributions"</strong> means any recurring or one-time payment obligation, levy, membership fee, donation, event payment, or similar amount that a Community requests from its Members through Glass.</li>
        <li><strong>"Payment Processor"</strong> means a licensed third-party payment service provider integrated with Glass, currently including Paystack, through which payment transactions are processed and settled.</li>
        <li><strong>"KYC Provider"</strong> means a licensed third-party identity verification provider integrated with Glass, currently including Smile ID.</li>
        <li><strong>"Platform"</strong> or <strong>"Services"</strong> means the Glass website, mobile applications, APIs, dashboards, and all related software and services.</li>
        <li><strong>"User Content"</strong> means any data, information, text, images, files, or other content submitted, uploaded, or generated by a User on the Platform.</li>
        <li><strong>"Applicable Law"</strong> means the laws of the Federal Republic of Nigeria and, where relevant to cross-border data processing or a User located outside Nigeria, any additional applicable data protection or consumer protection law.</li>
        <li><strong>"Affiliate"</strong> means any entity that controls, is controlled by, or is under common control with Glass Finance Limited.</li>
      </ul>

      <h2>2. Eligibility</h2>
      <p>
        2.1 You must be at least 18 years old, or the age of legal majority in your
        jurisdiction, to create an individual Glass Account. Users between 13 and 18 may
        participate as Members of a Community only under the supervision of a Community
        Administrator acting in accordance with Applicable Law, and may not independently
        register as Account holders or Community Owners.
      </p>
      <p>
        2.2 Organizations and Communities registering on Glass must be represented by an
        individual who has actual authority to bind that Organization or Community to this
        Agreement.
      </p>
      <p>
        2.3 You represent that you are not barred from using financial services under
        Applicable Law, including sanctions, anti-money laundering (AML), or counter-terrorist
        financing (CTF) restrictions, and that you are not listed on any sanctions list
        maintained by the Nigerian government, the United Nations, the U.S. Office of Foreign
        Assets Control (OFAC), the UK, or the European Union.
      </p>
      <p>
        2.4 Glass may, at its discretion, decline to open an Account or may close an existing
        Account where eligibility cannot be confirmed.
      </p>

      <h2>3. Account Registration</h2>
      <p>
        3.1 You agree to provide accurate, current, and complete information during
        registration and to keep such information up to date.
      </p>
      <p>
        3.2 You are responsible for maintaining the confidentiality of your login credentials
        and for all activity that occurs under your Account. Notify us immediately at the
        contact address in Section 33 if you suspect unauthorized access.
      </p>
      <p>
        3.3 One individual may not maintain multiple personal Accounts for the purpose of
        evading fees, limits, suspensions, or verification requirements.
      </p>
      <p>
        3.4 Glass may request additional information at any time to verify Account details, and
        may suspend an Account pending verification.
      </p>

      <h2>4. Identity Verification</h2>
      <p>
        4.1 Glass, directly or through KYC Providers such as Smile ID, may require identity
        verification ("KYC") before permitting certain actions, including creating a Community,
        collecting Dues above certain thresholds, or withdrawing funds.
      </p>
      <p>
        4.2 You authorize Glass to collect, use, and share identity information with KYC
        Providers, Payment Processors, and regulators as reasonably necessary to complete
        verification and comply with Applicable Law.
      </p>
      <p>
        4.3 Failure to complete requested verification may result in restricted functionality,
        delayed payouts, or Account suspension.
      </p>
      <p>
        4.4 Glass reserves the right to periodically re-verify identity information,
        particularly where transaction patterns, regulatory requirements, or risk indicators
        warrant re-verification.
      </p>

      <h2>5. Organization Accounts</h2>
      <p>
        5.1 A Community Owner registering on behalf of an Organization represents that they
        have authority to accept this Agreement and to designate Community Administrators.
      </p>
      <p>
        5.2 The Organization is responsible for the acts and omissions of its Community
        Administrators and Community Owners acting within the scope of their role on the
        Platform.
      </p>
      <p>
        5.3 Community Owners may assign the Community Administrator role to other users. The
        Platform currently supports three Community roles — Community Owner, Community
        Administrator, and Member — and Glass may introduce additional or more granular roles
        (such as Treasurer, Financial Officer, or Moderator) in the future. Glass is not
        responsible for internal governance disputes about who is authorized to hold or
        exercise a given role; the Organization bears sole responsibility for its internal
        governance and role assignment decisions.
      </p>
      <p>
        5.4 Where a Community Owner is removed, replaced, or disputed internally, Glass may
        require documentary evidence (such as a board resolution, minutes, or other governance
        record) before transferring administrative control, and may suspend administrative
        functions on the affected Community pending resolution.
      </p>

      <h2>6. Community Responsibilities</h2>
      <p>6.1 Communities and their Administrators are solely responsible for:</p>
      <ul>
        <li>determining the amount, frequency, and purpose of Dues and Contributions;</li>
        <li>determining their own membership rules and eligibility criteria;</li>
        <li>determining their own governance processes;</li>
        <li>determining their own refund policies toward Members (except where Glass itself processes a refund under the <Link to="/refund-policy">Refund Policy</Link>);</li>
        <li>ensuring that Dues collected are lawful, and are not used for money laundering, terrorist financing, unauthorized fundraising, gambling, or other purposes prohibited under the Acceptable Use Policy;</li>
        <li>resolving disputes among Community Members regarding use of collected funds.</li>
      </ul>
      <p>
        6.2 Glass provides software infrastructure only. Glass does not participate in,
        endorse, or take responsibility for a Community's internal decisions about how
        contributed funds are used, allocated, or governed.
      </p>
      <p>
        6.3 Communities must ensure that any representations made to Members about the purpose
        of a payment (e.g., "annual dues," "event fee," "donation") are accurate and not
        misleading.
      </p>

      <h2>7. Member Responsibilities</h2>
      <p>
        7.1 Members are responsible for providing accurate payment information and ensuring
        they have authority to use the payment method submitted.
      </p>
      <p>
        7.2 Members are responsible for understanding the terms set by their Community
        regarding Dues, refunds, and membership, which are separate from and in addition to
        this Agreement.
      </p>
      <p>
        7.3 Disputes between a Member and their Community regarding the underlying obligation
        (e.g., whether Dues are owed, or how funds are used) are the responsibility of the
        Community and its Members to resolve; Glass's role is limited to the technical
        processing and record-keeping of payments.
      </p>

      <h2>8. Payments</h2>
      <p>
        8.1 Glass enables Communities to request and collect payments from Members using
        Payment Processors. Glass itself is not a bank, is not currently a lender, is not a
        deposit-taking institution, is not a licensed microfinance bank, and does not offer
        investment products.
      </p>
      <p>
        8.2 All payments are processed by licensed Payment Processors. Glass does not directly
        custody Member funds; funds flow through the Payment Processor to the Community's
        designated settlement account, subject to applicable settlement timelines.
      </p>
      <p>
        8.3 By making a payment through Glass, you authorize Glass and its Payment Processors
        to process that transaction, including sharing necessary transaction and identity data
        with the Payment Processor.
      </p>

      <h2>9. Payment Processors</h2>
      <p>
        9.1 Payments on Glass are currently processed through Paystack. Glass may add, remove,
        or change Payment Processors at its discretion, and will provide reasonable notice of
        material changes affecting how Users transact.
      </p>
      <p>
        9.2 Payment Processors operate under their own terms of service and privacy policies,
        which apply in addition to this Agreement. Glass is not responsible for the acts,
        omissions, downtime, or errors of a Payment Processor, though Glass will make
        commercially reasonable efforts to assist Users in resolving processor-related issues.
      </p>
      <p>
        9.3 Settlement timelines, transaction limits, and reversal windows are governed in part
        by the Payment Processor's own operating rules and by the rules of the underlying card
        networks or bank transfer schemes, which may be outside Glass's control.
      </p>

      <h2>10. Recurring Payments</h2>
      <p>
        10.1 Communities may configure recurring Dues (e.g., monthly, termly, or annual). By
        enrolling in recurring Dues, a Member authorizes Glass and the applicable Payment
        Processor to initiate recurring charges against the Member's chosen payment method on
        the agreed schedule until the Member cancels, the Community ends the recurring
        arrangement, or the payment method fails.
      </p>
      <p>
        10.2 Members may cancel a recurring payment authorization at any time through the
        Platform. Cancellation takes effect for future billing cycles and does not
        automatically refund amounts already collected.
      </p>
      <p>
        10.3 Communities must give Members reasonable visibility into recurring Dues they are
        enrolled in, and Glass will provide dashboard tools to support this.
      </p>

      <h2>11. Failed Payments</h2>
      <p>
        11.1 A payment may fail due to insufficient funds, expired payment details, bank
        declines, network issues, or other reasons outside Glass's control.
      </p>
      <p>
        11.2 Glass may attempt to notify Members of failed payments and may support retry
        attempts, but does not guarantee successful collection of any Dues.
      </p>
      <p>
        11.3 Communities acknowledge that Glass is not responsible for a Member's failure to
        pay Dues, and that collection or enforcement of unpaid Dues outside the Platform (if
        any) is the Community's own responsibility, subject to Applicable Law.
      </p>

      <h2>12. Chargebacks</h2>
      <p>
        12.1 Where a Member disputes a transaction directly with their card issuer or bank (a
        "chargeback"), the Payment Processor's chargeback rules apply. Glass will cooperate
        with reasonable evidentiary requests from Payment Processors relating to a disputed
        transaction.
      </p>
      <p>
        12.2 Communities acknowledge that chargebacks may result in reversal of funds already
        settled, and that Glass or the Payment Processor may recover disputed amounts from a
        Community's future settlements, available balance, or by direct request to the
        Community, as applicable.
      </p>
      <p>
        12.3 Fraudulent or excessive chargeback activity attributable to a Community or its
        Members may result in restricted functionality or Account suspension under Section 21.
      </p>

      <h2>13. Taxes</h2>
      <p>
        13.1 Users are solely responsible for determining and fulfilling their own tax
        obligations arising from amounts collected, received, or paid through Glass, including
        any applicable value-added tax (VAT), withholding tax, or income tax under Nigerian law
        or other applicable jurisdictions.
      </p>
      <p>
        13.2 Glass does not provide tax advice. Communities that operate as charitable,
        religious, or non-profit entities are responsible for confirming and maintaining any
        tax-exempt status they claim.
      </p>
      <p>
        13.3 Glass may be required by Applicable Law to report certain transaction data to tax
        authorities and will comply with such lawful obligations.
      </p>

      <h2>14. Fees</h2>
      <p>
        14.1 Glass charges fees for use of the Platform, which may include a markup applied to
        Member payments so that Communities receive the full intended Dues amount ("Top-Up Fee
        Model"), platform subscription fees, or other fee structures as published from time to
        time in Glass's current pricing documentation.
      </p>
      <p>
        14.2 Payment Processor fees (e.g., Paystack transaction fees) are separate from Glass's
        own fees and may be absorbed into Glass's fee structure or passed through, as described
        in the applicable pricing terms in effect at the time of the transaction.
      </p>
      <p>
        14.3 Glass will make its current fee structure available to Users through the Platform
        or upon request, and will provide reasonable advance notice before increasing fees on
        existing recurring arrangements.
      </p>
      <p>14.4 All fees are exclusive of applicable taxes unless stated otherwise.</p>

      <h2>15. Platform Availability</h2>
      <p>
        15.1 Glass will use commercially reasonable efforts to keep the Platform available but
        does not guarantee uninterrupted or error-free operation. The Platform may be
        unavailable due to maintenance, updates, third-party outages (including Payment
        Processor or cloud infrastructure outages), or circumstances beyond Glass's reasonable
        control.
      </p>
      <p>
        15.2 Glass is not liable for losses arising from scheduled maintenance or unplanned
        downtime, except to the extent caused by Glass's gross negligence or willful
        misconduct.
      </p>

      <h2>16. User Content</h2>
      <p>
        16.1 Users retain ownership of User Content they submit, including Community names,
        descriptions, logos, and Member lists, subject to the license granted in Section 18.2.
      </p>
      <p>
        16.2 Users are responsible for ensuring that User Content does not infringe
        third-party rights, is not defamatory, unlawful, or misleading, and complies with the
        Acceptable Use Policy.
      </p>
      <p>
        16.3 Glass may remove or restrict access to User Content that violates this Agreement,
        upon notice where reasonably practicable.
      </p>

      <h2>17. Intellectual Property</h2>
      <p>
        17.1 The Platform, including its software, design, trademarks (including "Glass" and
        associated logos), and underlying technology, is owned by Glass Finance Limited or its
        licensors and is protected by Nigerian and international intellectual property law.
      </p>
      <p>
        17.2 Nothing in this Agreement transfers ownership of Glass's intellectual property to
        any User. Users receive only the limited license described in Section 18.
      </p>

      <h2>18. Software License</h2>
      <p>
        18.1 Subject to compliance with this Agreement, Glass grants Users a limited,
        non-exclusive, non-transferable, revocable license to access and use the Platform for
        its intended purpose.
      </p>
      <p>
        18.2 By submitting User Content, Users grant Glass a worldwide, non-exclusive,
        royalty-free license to host, store, process, display, and transmit that content
        solely as necessary to operate and improve the Platform, and in accordance with the
        Privacy Policy.
      </p>
      <p>
        18.3 Users may not copy, modify, reverse-engineer, decompile, resell, sublicense, or
        create derivative works of the Platform, except as expressly permitted by Glass or by
        Applicable Law.
      </p>

      <h2>19. Acceptable Conduct</h2>
      <p>
        Users must comply with the <Link to="/acceptable-use">Acceptable Use Policy</Link>,
        which is incorporated into this Agreement by reference and governs prohibited
        activities on the Platform.
      </p>

      <h2>20. Fraud Prevention</h2>
      <p>
        20.1 Glass employs fraud detection, transaction monitoring, and identity verification
        measures to protect Users and the integrity of the Platform.
      </p>
      <p>
        20.2 Glass may delay, decline, reverse, or investigate any transaction reasonably
        suspected of being fraudulent, unauthorized, or in violation of this Agreement, and may
        report suspected fraud to Payment Processors, regulators, or law enforcement as
        required by Applicable Law.
      </p>
      <p>
        20.3 Users must promptly report suspected fraudulent activity on their Account to Glass
        through the channels in Section 33.
      </p>

      <h2>21. Account Suspension</h2>
      <p>21.1 Glass may suspend, restrict, or limit an Account's functionality where Glass reasonably believes:</p>
      <ul>
        <li>the Account is being used fraudulently or in violation of this Agreement or the Acceptable Use Policy;</li>
        <li>suspension is necessary to comply with Applicable Law, a regulator, or a law enforcement request;</li>
        <li>suspension is necessary to protect the security or integrity of the Platform or other Users;</li>
        <li>identity verification is incomplete or has failed;</li>
        <li>a Payment Processor or KYC Provider has flagged the Account or an associated transaction.</li>
      </ul>
      <p>
        21.2 Where reasonably practicable and lawful, Glass will notify the affected User of a
        suspension and the general reason for it, and will provide a channel to seek
        reinstatement.
      </p>
      <p>
        21.3 Suspension of an Account does not, by itself, terminate the underlying obligations
        between a Community and its Members, which remain governed by the Community's own
        arrangements.
      </p>

      <h2>22. Termination</h2>
      <p>
        22.1 Users may close their Account at any time by contacting Glass through the
        channels in Section 33, subject to completion of any pending transactions, settlement
        obligations, or regulatory holds.
      </p>
      <p>
        22.2 Glass may terminate or suspend an Account, with or without notice, for material
        breach of this Agreement, prolonged inactivity, legal or regulatory requirements, or
        where continued provision of the Services to that User would expose Glass to legal or
        reputational risk.
      </p>
      <p>
        22.3 Upon termination, Glass will take reasonable steps to complete or reverse pending
        transactions in accordance with Applicable Law and Payment Processor rules, and will
        retain records as required under Section 15 (Retention) of the Privacy Policy.
      </p>

      <h2>23. Third-Party Services</h2>
      <p>
        23.1 The Platform integrates with third-party services, currently including Paystack
        (payments), Smile ID (identity verification), Resend (email), Termii (SMS), AWS (cloud
        infrastructure), Vercel (hosting), and Google Workspace (productivity tools). This list
        may change over time.
      </p>
      <p>
        23.2 Use of third-party services is subject to those providers' own terms and privacy
        policies. Glass is not responsible for the acts or omissions of independent third-party
        providers, but will exercise reasonable care in selecting providers that meet
        applicable regulatory and security standards.
      </p>

      <h2>24. Privacy</h2>
      <p>
        Glass's collection, use, and disclosure of personal information is governed by the{" "}
        <Link to="/privacy">Privacy Policy</Link> and <Link to="/cookies">Cookie Policy</Link>,
        which are incorporated into this Agreement by reference.
      </p>

      <h2>25. Disclaimers</h2>
      <p>
        25.1 THE PLATFORM IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTIES OF ANY
        KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING WARRANTIES OF MERCHANTABILITY,
        FITNESS FOR A PARTICULAR PURPOSE, TITLE, OR NON-INFRINGEMENT, EXCEPT WHERE SUCH
        DISCLAIMERS ARE PROHIBITED BY APPLICABLE LAW.
      </p>
      <p>
        25.2 Glass does not guarantee that the Platform will be error-free, secure, or
        uninterrupted, or that any Payment Processor or KYC Provider will operate without
        error.
      </p>
      <p>
        25.3 Glass is a technology provider. Glass does not guarantee the conduct, solvency,
        honesty, or governance practices of any Community, Community Administrator, or Member.
      </p>

      <h2>26. Limitation of Liability</h2>
      <p>
        26.1 TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, GLASS AND ITS AFFILIATES,
        OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT,
        INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS,
        REVENUE, DATA, OR GOODWILL, ARISING FROM OR RELATED TO YOUR USE OF THE PLATFORM.
      </p>
      <p>
        26.2 GLASS'S TOTAL AGGREGATE LIABILITY TO ANY USER FOR CLAIMS ARISING FROM OR RELATED
        TO THIS AGREEMENT SHALL NOT EXCEED THE GREATER OF (A) THE TOTAL FEES PAID BY THAT USER
        TO GLASS IN THE SIX (6) MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM, OR (B) TEN
        THOUSAND NAIRA (₦10,000).
      </p>
      <p>
        26.3 Nothing in this Agreement excludes or limits liability that cannot be excluded or
        limited under Applicable Law, including liability for death, personal injury caused by
        negligence, fraud, or fraudulent misrepresentation.
      </p>
      <p>
        26.4 This limitation applies regardless of the legal theory of liability (contract,
        tort, negligence, strict liability, or otherwise) and even if Glass has been advised of
        the possibility of such damages.
      </p>

      <h2>27. Indemnification</h2>
      <p>
        You agree to indemnify, defend, and hold harmless Glass and its Affiliates, officers,
        directors, employees, and agents from and against any claims, liabilities, damages,
        losses, and expenses (including reasonable legal fees) arising out of or related to:
        (a) your use of the Platform; (b) your violation of this Agreement or Applicable Law;
        (c) your violation of any third-party right; or (d) User Content you submit, except to
        the extent caused by Glass's gross negligence or willful misconduct.
      </p>

      <h2>28. Force Majeure</h2>
      <p>
        Glass shall not be liable for any failure or delay in performance resulting from causes
        beyond its reasonable control, including acts of God, natural disasters, war,
        terrorism, riots, civil unrest, government action, changes in Applicable Law, labor
        disputes, internet or telecommunications failures, power outages, or failures of
        third-party providers such as Payment Processors, cloud providers, or KYC Providers.
      </p>

      <h2>29. Changes to Terms</h2>
      <p>
        29.1 Glass may update this Agreement from time to time to reflect changes in the
        Platform, legal requirements, or business practices.
      </p>
      <p>
        29.2 Material changes will be communicated through the Platform, email, or other
        reasonable means, with an updated "Last Updated" date, and where required by Applicable
        Law, with advance notice before the changes take effect.
      </p>
      <p>
        29.3 Continued use of the Platform after changes take effect constitutes acceptance of
        the revised Agreement. If you do not agree to the changes, you must stop using the
        Platform and may close your Account.
      </p>

      <h2>30. Notices</h2>
      <p>
        30.1 Glass may provide notices to Users via email, in-app notification, SMS, or by
        posting on the Platform.
      </p>
      <p>
        30.2 Users must provide notices to Glass in writing via the contact details in Section
        33.
      </p>

      <h2>31. Governing Law</h2>
      <p>
        This Agreement is governed by and construed in accordance with the laws of the Federal
        Republic of Nigeria, without regard to conflict-of-law principles.
      </p>

      <h2>32. Dispute Resolution</h2>
      <p>
        32.1 Glass encourages Users to first attempt to resolve any dispute informally by
        contacting Glass through the channels in Section 33.
      </p>
      <p>
        32.2 If a dispute cannot be resolved informally within thirty (30) days, either party
        may pursue resolution through arbitration under the Arbitration and Mediation Act 2023
        (or its successor legislation), seated in Lagos, Nigeria, with proceedings conducted in
        English, unless the parties agree in writing to another mechanism.
      </p>
      <p>
        32.3 Notwithstanding Section 32.2, either party may seek injunctive or equitable relief
        in the courts of Lagos State, Nigeria, where necessary to prevent irreparable harm,
        including in cases of suspected fraud or misuse of the Platform.
      </p>
      <p>
        32.4 Nothing in this Section limits a User's statutory rights to lodge a complaint with
        a competent regulator, including the Central Bank of Nigeria (CBN) or the Nigeria Data
        Protection Commission (NDPC).
      </p>

      <h2>33. Contact Information</h2>
      <p>
        Glass Finance Limited<br />
        Email: <a href="mailto:legal@glasspay.app">legal@glasspay.app</a><br />
        Support: <a href="mailto:support@glasspay.app">support@glasspay.app</a><br />
        Address: 1, Onyemergwu Close, Abule Egba, Lagos
      </p>

      <h2>34. Severability</h2>
      <p>
        If any provision of this Agreement is held invalid or unenforceable, that provision
        will be limited or eliminated to the minimum extent necessary, and the remaining
        provisions will remain in full force and effect.
      </p>

      <h2>35. Entire Agreement</h2>
      <p>
        This Agreement, together with the <Link to="/privacy">Privacy Policy</Link>,{" "}
        <Link to="/cookies">Cookie Policy</Link>,{" "}
        <Link to="/acceptable-use">Acceptable Use Policy</Link>,{" "}
        <Link to="/refund-policy">Refund Policy</Link>, and any additional terms referenced
        herein, constitutes the entire agreement between you and Glass regarding the Platform,
        and supersedes any prior agreements or understandings.
      </p>

      <h2>36. Survival</h2>
      <p>
        Provisions that by their nature should survive termination — including Sections 13
        (Taxes), 17 (Intellectual Property), 26 (Limitation of Liability), 27
        (Indemnification), 31 (Governing Law), and 32 (Dispute Resolution) — will survive
        termination or expiration of this Agreement.
      </p>
    </LegalPageLayout>
  );
}
